import '../styles/globals.css'
import Head from 'next/head'
import Header from '../components/Header'
import Navbar from '../components/Navbar'


function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>dipesh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
      <Header />
      <Navbar />
      < Component {...pageProps} />
    </>
  )
}

export default MyApp
